name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-linux-musl
            artifact: neonx-linux-x64
            binary: neonx

          - target: aarch64-linux-musl
            artifact: neonx-linux-arm64
            binary: neonx

          - target: x86_64-windows-gnu
            artifact: neonx-windows-x64
            binary: neonx.exe

          - target: arm-linux-musleabihf
            artifact: neonx-linux-arm32
            binary: neonx

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Compile with build.sh
        run: |
          bash build.sh --target ${{ matrix.target }} --output ${{ matrix.binary }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: build/${{ matrix.binary }}
