name: NeonX Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Baixar o código do repositório
      uses: actions/checkout@v4

    - name: ⚡ Instalar Zig Compiler
      uses: mlugg/setup-zig@v1
      with:
        version: 0.11.0

    - name: 🔑 Dar permissão de execução aos scripts
      run: |
        chmod +x build.sh
        chmod +x verify_public.sh

    - name: 🔨 Compilar o Arsenal Completo (--ci)
      run: ./build.sh --ci

    - name: 🧪 Testar Execução (Linux x64)
      run: |
        echo "Teste de Inicialização..."
        ./build/neonx_linux_x64 --version
        
    - name: 🧪 Testar Pipeline de Cor (Modo Estático)
      run: |
        echo "Validando Shaders..."
        echo "NeonX Blindado e Operante!" | ./build/neonx_linux_x64 -S -m 1
